### ISSUE TITLE
Cached IPFS sites with gateway

### ISSUE THREAD

**Issue by solleedev** [dappnetbby/dappnet-features#23]
idea:

- dappnet hosts a custom IPFS gateway
- the dappnet client automatically downloads from there, but checks hash of website against IPFS to ensure nothing is tampered with
- gateway should cache frequently used IPFS sites and update on change
- if gateway is down, connect to IPFS network as fallback

**Comment by liamzebedee** [comment]
Hey @solleedev, thanks for contributing!

I believe there might be a confusion in your understanding.

Dappnet runs an IPFS node `kubo`, which includes an IPFS gateway. All content downloaded from the gateway at `http://localhost:8080/ipfs/bayfXXXXXXX` is automatically cached as part of `kubo`'s logic, and downloaded from the IPFS network.
